# Created with package:mono_repo v3.0.1-dev
name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  job_001:
    name: "OS: linux; SDK: dev; PKG: mono_repo; TASKS: `cd ../ && dart mono_repo/bin/mono_repo.dart travis --validate`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo
          TRAVIS_OS_NAME: linux
        run: tool/travis.sh command
  job_002:
    name: "OS: linux; SDK: dev; PKGS: mono_repo, test_pkg; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --fatal-infos --fatal-warnings .`]"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo test_pkg
          TRAVIS_OS_NAME: linux
        run: tool/travis.sh dartfmt dartanalyzer_0
  job_003:
    name: "OS: linux; SDK: 2.7.0; PKG: mono_repo; TASKS: `dartanalyzer --fatal-warnings .`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.7.0"
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo
          TRAVIS_OS_NAME: linux
        run: tool/travis.sh dartanalyzer_1
  job_004:
    name: "OS: linux; SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.7.0"
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo
          TRAVIS_OS_NAME: linux
        run: tool/travis.sh test_0
  job_005:
    name: "OS: windows; SDK: 2.7.0; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: "2.7.0"
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo
          TRAVIS_OS_NAME: windows
        run: tool/travis.sh test_0
  job_006:
    name: "OS: linux; SDK: dev; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo
          TRAVIS_OS_NAME: linux
        run: tool/travis.sh test_0
  job_007:
    name: "OS: windows; SDK: dev; PKG: mono_repo; TASKS: `pub run test -P presubmit --test-randomize-ordering-seed=random`"
    runs-on: windows-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: mono_repo
          TRAVIS_OS_NAME: windows
        run: tool/travis.sh test_0
  job_008:
    name: "OS: linux; SDK: dev; PKG: test_pkg; TASKS: `pub run test --test-randomize-ordering-seed=random`"
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - uses: actions/checkout@v2
      - env:
          PKGS: test_pkg
          TRAVIS_OS_NAME: linux
        run: tool/travis.sh test_1
